name: üîÄ Test Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  node-pipeline:
    name: üîç Test
    uses: ./.github/workflows/node.js.yml
    if: true # easily disable if needed
    with:
      actions-branch: main
      mock-run: true
    secrets:
      READ_WRITE_PACKAGES_GITHUB_TOKEN: ${{ secrets.READ_WRITE_PACKAGES_GITHUB_TOKEN }}

  gradle-pipeline:
    name: üîç Test
    uses: ./.github/workflows/gradle.yml
    if: true # easily disable if needed
    with:
      actions-branch: main
      mock-run: true
    secrets:
      READ_WRITE_PACKAGES_GITHUB_TOKEN: ${{ secrets.READ_WRITE_PACKAGES_GITHUB_TOKEN }}

  gradle-lib-pipeline:
    name: üîç Test
    uses: ./.github/workflows/gradle.lib.yml
    if: true # easily disable if needed
    with:
      actions-branch: main
      mock-run: true
    secrets:
      READ_WRITE_PACKAGES_GITHUB_TOKEN: ${{ secrets.READ_WRITE_PACKAGES_GITHUB_TOKEN }}

  cicd-pipeline:
    name: ‚ñ∂Ô∏è Run CICD pipeline
    runs-on: ubuntu-latest
    needs:
      - gradle-pipeline
      - gradle-lib-pipeline
      - node-pipeline

    steps:
      - name: üöö Prepare release
        uses: googleapis/release-please-action@v4
        id: release
        if: ${{env.SKIP_RELEASE == ''}}
        with:
          token: ${{ github.token }}

