name: ğŸ”€ Test Pipeline

on:
  push:
    branches-ignore:
      - 'release-please--branches--main'
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - 'main'

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:

  pipeline:
    name: ğŸ” Test
    uses: ./.github/workflows/pipeline.yaml

  release:
    name: ğŸ” Test
    uses: ./.github/workflows/release.yaml
    secrets:
      READ_WRITE_PACKAGES_GITHUB_TOKEN: ${{ secrets.READ_WRITE_PACKAGES_GITHUB_TOKEN }}

  test-pipeline:
    name: â–¶ï¸ Run CI pipeline
    runs-on: ubuntu-latest
    needs:
      - pipeline