on:
  workflow_call:
    inputs:
      actions-branch:
        required: true
        type: string
      mock-run:
        required: false
        type: boolean
        default: false
    secrets:
      READ_WRITE_PACKAGES_GITHUB_TOKEN:
        required: true

env:
  READ_WRITE_PACKAGES_GITHUB_ACTOR: ''
  READ_WRITE_PACKAGES_GITHUB_TOKEN: ${{ secrets.READ_WRITE_PACKAGES_GITHUB_TOKEN }}

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:

  gradle-common-pipeline:
    name: ğŸ”€ Test
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.create-build-info.outputs.version }}
      release-created: ${{ steps.release.outputs.release_created }}

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: ğŸ› ï¸ Checkout actions
        uses: actions/checkout@v4
        with:
          repository: Tomasz-Marciniak/github-actions-starter
          path: github-actions-starter
          ref: ${{ inputs.actions-branch }}
          token: ${{ secrets.READ_WRITE_PACKAGES_GITHUB_TOKEN }}
          sparse-checkout: |
            .github/actions/create-build-info
            .github/actions/setup-docker-tags

      - name: ğŸ—‘ï¸ Delete packages
        uses: actions/delete-package-versions@v5
        if: ${{ !inputs.mock-run }}
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: "true"
          token: ${{ github.token }}

      - name: ğŸ’¾ Copy actions
        if: ${{ !inputs.mock-run }}
        run: mkdir -p ".github/actions" && cp -r github-actions-starter/.github/actions/* .github/actions

      - name: ğŸ¤– Setup mocks
        if: ${{ inputs.mock-run }}
        run: |
          cp ./mocks/gradle/* .
          cp -r ./mocks/gradle/.gradle ~
          cp ./docker/Dockerfile ./docker/Dockerfile.jvm

      - name: ğŸšš Prepare release
        uses: google-github-actions/release-please-action@v4
        id: release
        if: ${{ !inputs.mock-run }}
        with:
          token: ${{ github.token }}

      - name: ğŸ“‹ Create build information
        uses: ./.github/actions/create-build-info
        id: create-build-info
        with:
          release-created: ${{ steps.release.outputs.release_created }}
          release-version: v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
          output-file: git.properties

      - name: ğŸ”‹ Set up Graal VM 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: gradle
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ”§ Build with Gradle
        shell: bash
        run: ./gradlew clean classes

      - name: ğŸ” Run tests
        run: ./gradlew check

      - name: ğŸ—œï¸ Archive test reports
        uses: actions/upload-artifact@v4
        if: ${{ !inputs.mock-run }}
        with:
          name: tests-report
          path: ./build/reports/tests

      - name: â™»ï¸ Cache build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: ./build
          key: ${{ github.run_id }}

  gradle-jar-pipeline:
    name: ğŸ”€ JAR image
    runs-on: ubuntu-latest
    needs: [gradle-common-pipeline]
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: ğŸ› ï¸ Checkout actions
        uses: actions/checkout@v4
        with:
          repository: Tomasz-Marciniak/github-actions-starter
          path: github-actions-starter
          ref: ${{ inputs.actions-branch }}
          token: ${{ secrets.READ_WRITE_PACKAGES_GITHUB_TOKEN }}
          sparse-checkout: |
            .github/actions/setup-docker-tags

      - name: ğŸ’¾ Copy actions
        if: ${{ !inputs.mock-run }}
        run: mkdir -p ".github/actions" && cp -r github-actions-starter/.github/actions/* .github/actions

      - name: Cache build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: ./build
          key: ${{ github.run_id }}

      - name: ğŸ¤– Setup mocks
        if: ${{ inputs.mock-run }}
        run: |
          cp ./mocks/gradle/* .
          cp -r ./mocks/gradle/.gradle ~
          cp ./docker/Dockerfile ./docker/Dockerfile.jvm

      - name: ğŸ”‹ Set up Graal VM 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: gradle
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ“¦ Run production packaging
        run: ./gradlew bootJar

      - name: ğŸ”¢ Set up tags
        uses: ./.github/actions/setup-docker-tags
        id: setup-docker-tags
        with:
          release-created: ${{needs.gradle-common-pipeline.outputs.release-created}}
          version: ${{needs.gradle-common-pipeline.outputs.version}}

      - name: ğŸ’» Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: ğŸ‘·â€â™‚ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ” Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: ğŸ· Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: ${{ steps.setup-docker-tags.outputs.docker-tags }}

      - name: ğŸ‹ Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.jvm
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

  graal-native:
    name: ğŸ”€ GraalVM image
    runs-on: ubuntu-latest
    needs: [ gradle-common-pipeline ]
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: ğŸ› ï¸ Checkout actions
        uses: actions/checkout@v4
        with:
          repository: Tomasz-Marciniak/github-actions-starter
          path: github-actions-starter
          ref: ${{ inputs.actions-branch }}
          token: ${{ secrets.READ_WRITE_PACKAGES_GITHUB_TOKEN }}
          sparse-checkout: |
            .github/actions/setup-docker-tags

      - name: ğŸ’¾ Copy actions
        if: ${{ !inputs.mock-run }}
        run: mkdir -p ".github/actions" && cp -r github-actions-starter/.github/actions/* .github/actions

      - name: â™»ï¸ Cache build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ github.run_id }}

      - name: ğŸ¤– Setup mocks
        if: ${{ inputs.mock-run }}
        run: |
          cp ./mocks/gradle/* .
          cp -r ./mocks/gradle/.gradle ~
          cp ./docker/Dockerfile ./docker/Dockerfile.native
          cp ./docker/Dockerfile ./docker/Dockerfile.jvm

      - name: ğŸ”‹ Set up Graal VM 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: gradle
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸš€ Build native image with Gradle
        run: ./gradlew nativeCompile

      - name: ğŸ”¢ Set up tags
        uses: ./.github/actions/setup-docker-tags
        id: setup-docker-tags
        with:
          release-created: ${{needs.gradle-common-pipeline.outputs.release-created}}
          version: ${{needs.gradle-common-pipeline.outputs.version}}
          suffix: '-native'

      - name: ğŸ’» Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: ğŸ‘·â€â™‚ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ” Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: ğŸ· Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: ${{ steps.setup-docker-tags.outputs.docker-tags }}

      - name: ğŸ‹ Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.native
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max