name: Node.js Pipeline

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  node-pipeline:
    name: Node.js pipeline
    runs-on: ubuntu-latest

    env:
      AXON_BRAVE_OBSERVABILITY_GITHUB_ACTOR: ${{ secrets.AXON_BRAVE_OBSERVABILITY_GITHUB_ACTOR }}
      AXON_BRAVE_OBSERVABILITY_GITHUB_TOKEN: ${{ secrets.AXON_BRAVE_OBSERVABILITY_GITHUB_TOKEN }}

    permissions:
      contents: write
      pull-requests: write
      packages: write

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: ğŸšš Prepare release
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ github.token }}

      - name: ğŸ“‹ Create build information
        uses: ./.github/actions/build-info
        id: build-info
        with:
          is-release: ${{ steps.release.outputs.release_created }}
          output-file: git.properties

      - name: ğŸ”‹ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
          cache: gradle

      - name: ğŸ”§ Build with Gradle
        shell: bash
        run: ./gradlew clean classes

      - name: ğŸ“‹ Run tests
        run: ./gradlew check

      - name: ğŸ“ Archive test reports
        uses: actions/upload-artifact@v4
        with:
          name: tests-report
          path: ./build/reports/tests

      - name: ğŸ“¦ Run production packaging
        if: ${{ steps.release.outputs.release_created != 'true' }}
        run: ./gradlew bootJar

      - name: Build native image with Gradle
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: ./gradlew nativeCompile

      - name: ğŸ”¢ Set up tags
        uses: ./.github/actions/setup-docker-tags
        id: setup-docker-tags
        with:
          is-release: ${{ steps.release.outputs.release_created }}
          version: ${{ steps.build-info.outputs.version }}

      - name: ğŸ’» Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: ğŸ‘·â€â™‚ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ” Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ· Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: ${{ steps.setup-docker-tags.outputs.docker-tags }}

      - name: ğŸ‹ Build and push
        uses: docker/build-push-action@v5
        if: ${{ steps.release.outputs.release_created == 'true' }}
        with:
          context: .
          file: docker/Dockerfile.native
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}-native
          labels: ${{ steps.meta.outputs.labels }}-native
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: ğŸ‹ Build and push
        uses: docker/build-push-action@v5
        if: ${{ steps.release.outputs.release_created != 'true' }}
        with:
          context: .
          file: docker/Dockerfile.jvm
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max