on:
  workflow_call:
    secrets:
      READ_WRITE_PACKAGES_GITHUB_TOKEN:
        required: true
    inputs:
      library:
        required: false
        type: boolean
        default: false
      native:
        required: false
        type: boolean
        default: false

env:
  READ_WRITE_PACKAGES_GITHUB_ACTOR: ''
  READ_WRITE_PACKAGES_GITHUB_TOKEN: ${{ secrets.READ_WRITE_PACKAGES_GITHUB_TOKEN }}

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  gradle-build:
    name: ğŸ˜ Gradle build
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4

      - name: ğŸ“‹ Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: â™»ï¸ Cache build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: ./build
          key: ${{ github.run_id }}

      - name: ğŸ”‹ Set up Graal VM 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: gradle
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ” Run tests
        run: ./gradlew build -x check

      - name: ğŸ—œï¸ Archive reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report${{ inputs.library && '-library' || '' }}
          path: ./build/reports

      - name: ğŸ“¦ Run production packaging
        if: ${{ !inputs.library }}
        run: ./gradlew bootJar

      - name: ğŸš€ Build native image with Gradle
        if: ${{ inputs.native }}
        run: ./gradlew nativeCompile

      - name: â¬†ï¸ Publish package
        if: ${{ inputs.library }}
        run: ./gradlew publish

      - name: ğŸ’» Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: ğŸ‘·â€â™‚ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ” Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ· Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: ğŸ‹ Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.jvm
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: ğŸ· Extract metadata for Docker
        id: meta-native
        if: ${{ inputs.native }}
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          flavor:
            suffix=-native

      - name: ğŸ‹ Build and push
        uses: docker/build-push-action@v5
        if: ${{ inputs.native }}
        with:
          context: .
          file: docker/Dockerfile.native
          push: true
          tags: ${{ steps.meta-native.outputs.tags }}
          labels: ${{ steps.meta-native.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max