on:
  workflow_call:
    inputs:
      actions-branch:
        required: true
        type: string
      mock-run:
        required: false
        type: boolean
        default: false
    secrets:
      AXON_BRAVE_OBSERVABILITY_GITHUB_TOKEN:
        required: true
      READ_WRITE_PACKAGES_TOKEN:
        required: true

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  gradle-pipeline:
    name: ğŸ”€ Gradle pipeline
    runs-on: ubuntu-latest

    env:
      AXON_BRAVE_OBSERVABILITY_GITHUB_ACTOR: ''
      AXON_BRAVE_OBSERVABILITY_GITHUB_TOKEN: ${{ secrets.AXON_BRAVE_OBSERVABILITY_GITHUB_TOKEN }}

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: ğŸ› ï¸ Checkout actions
        uses: actions/checkout@v4
        with:
          repository: Tomasz-Marciniak/github-actions-starter
          path: github-actions-starter
          ref: ${{ inputs.actions-branch }}
          token: ${{ secrets.READ_WRITE_PACKAGES_TOKEN }}
          sparse-checkout: |
            .github/actions/create-build-info
            .github/actions/gradle-run-tests
            .github/actions/setup-docker-tags

      - name: ğŸ’¾ Copy actions
        if: ${{ !inputs.mock-run }}
        run: mkdir -p ".github/actions" && cp -r github-actions-starter/.github/actions/* .github/actions

      - name: ğŸ¤– Setup mocks
        if: ${{ inputs.mock-run }}
        run: |
          cp ./mocks/gradle/* .
          cp -r ./mocks/gradle/.gradle ~
          cp ./docker/Dockerfile ./docker/Dockerfile.native
          cp ./docker/Dockerfile ./docker/Dockerfile.jvm

      - name: ğŸšš Prepare release
        uses: google-github-actions/release-please-action@v4
        id: release
        if: ${{ !inputs.mock-run }}
        with:
          token: ${{ github.token }}

      - name: ğŸ“‹ Create build information
        uses: ./.github/actions/create-build-info
        id: create-build-info
        with:
          is-release: ${{ steps.release.outputs.release_created }}
          output-file: git.properties

      - name: ğŸ”‹ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto
          cache: gradle

      - name: ğŸ”§ Build with Gradle
        shell: bash
        run: ./gradlew clean classes

      - name: ğŸ” Run tests
        run: ./gradlew check

      - name: ğŸ—œï¸ Archive test reports
        uses: actions/upload-artifact@v4
        if: ${{ !inputs.mock-run }}
        with:
          name: tests-report
          path: ./build/reports/tests

      - name: ğŸ“¦ Run production packaging
        if: ${{ steps.release.outputs.release_created != 'true' }}
        run: ./gradlew bootJar

      - name: ğŸš€ Build native image with Gradle
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: ./gradlew nativeCompile

      - name: ğŸ”¢ Set up tags
        uses: ./.github/actions/setup-docker-tags
        id: setup-docker-tags
        with:
          is-release: ${{ steps.release.outputs.release_created }}
          version: ${{ steps.create-build-info.outputs.version }}
          suffix: ${{ steps.release.outputs.release_created && '-native' || ''}}

      - name: ğŸ’» Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: ğŸ‘·â€â™‚ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ” Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: ğŸ· Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: ${{ steps.setup-docker-tags.outputs.docker-tags }}

      - name: ğŸ‹ Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ steps.release.outputs.release_created == 'true' && 'docker/Dockerfile.native' || 'docker/Dockerfile'}}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: ğŸ—‘ï¸ Delete packages
        uses: actions/delete-package-versions@v5
        if: ${{ !inputs.mock-run }}
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-pre-release-versions: "true"
          token: ${{ github.token }}