name: Java Library CI with Gradle

on:
  push:
    tags:
      - v*.*.*
  pull_request:
  workflow_call:
    secrets:
      READ_WRITE_PACKAGES_GITHUB_TOKEN:
        required: true

env:
  READ_WRITE_PACKAGES_GITHUB_ACTOR: ''
  READ_WRITE_PACKAGES_GITHUB_TOKEN: ${{ secrets.READ_WRITE_PACKAGES_GITHUB_TOKEN }}

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  gradle-build:
    name: ğŸ˜ Gradle build
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4

      - name: ğŸ“‹ Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: â™»ï¸ Cache build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: ./build
          key: ${{ github.run_id }}

      - name: ğŸ”‹ Set up Graal VM 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: gradle
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ“¦ Run build
        run: ./gradlew build

      - name: ğŸ—œï¸ Archive reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report
          path: ./build/reports

      - name: â¬†ï¸ Publish package
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: ./gradlew publish