name: Node Pipeline

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  node-pipeline:
    name: Node pipeline
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      packages: write

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4

      - name: ğŸ”‹ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: ğŸ“ Cache node modules
        uses: ./.github/actions/cache-node-modules
        id: cache-node-modules

      - name: ğŸ”§ Run clean install
        run: npm ci
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}

      - name: ğŸ“‹ Run tests
        run: npm run test

      - name: ğŸ“¦ Run production packaging
        run: npm run dist

      - name: ğŸšš Prepare release
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ github.token }}

      - name: ğŸ”¢ Set up tags
        uses: ./.github/actions/setup-tags
        id: setup-tags
        with:
          is-release: ${{ steps.release.outputs.release_created }}
          version: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}

      - name: ğŸ’» Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: ğŸ‘·â€â™‚ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ” Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ· Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: ${{ steps.setup-tags.outputs.tags }}

      - name: ğŸ‹ Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.nginx
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max