on:
  workflow_call:
    inputs:
      actions-branch:
        required: true
        type: string
      mock-run:
        required: false
        type: boolean
        default: false
    secrets:
      READ_WRITE_PACKAGES_GITHUB_TOKEN:
        required: true

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  node-pipeline:
    name: ğŸ”€ Node.js pipeline
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: ğŸ› ï¸ï¸ Checkout actions
        uses: actions/checkout@v4
        with:
          repository: intosoft-tm/github-actions-starter
          path: github-actions-starter
          ref: ${{ inputs.actions-branch }}
          token: ${{ secrets.READ_WRITE_PACKAGES_GITHUB_TOKEN }}
          sparse-checkout: |
            .github/actions/cache-node-modules
            .github/actions/create-build-info
            .github/actions/setup-docker-tags

      - name: ğŸ’¾ Copy actions
        if: ${{ !inputs.mock-run }}
        run: mkdir -p ".github/actions" && cp -r github-actions-starter/.github/actions/* .github/actions

      - name: ğŸ¤– Setup mocks
        if: ${{ inputs.mock-run }}
        run: |
          cp ./mocks/node.js/* ./
          cp ./docker/Dockerfile ./docker/Dockerfile.nginx

      - name: ğŸšš Prepare release
        uses: googleapis/release-please-action@v4
        id: release
        if: ${{ !inputs.mock-run }}
        with:
          token: ${{ github.token }}

      - name: ğŸ“‹ Create build information
        uses: ./.github/actions/create-build-info
        id: create-build-info
        with:
          release-created: ${{ steps.release.outputs.release_created }}
          release-version: v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
          output-file: git.properties

      - name: ğŸ”‹ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: â™»ï¸ Cache node modules
        uses: ./.github/actions/cache-node-modules
        id: cache-node-modules

      - name: ğŸ”§ Run clean install
        run: npm ci
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}

      - name: ğŸ” Run tests
        run: npm run test

      - name: ğŸ“¦ Run production packaging
        run: npm run dist

      - name: ğŸ”¢ Set up tags
        uses: ./.github/actions/setup-docker-tags
        id: setup-docker-tags
        with:
          release-created: ${{ steps.release.outputs.release_created }}
          version: ${{ steps.create-build-info.outputs.version }}

      - name: ğŸ’» Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: ğŸ‘·â€â™‚ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ” Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: ğŸ· Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: ${{ steps.setup-docker-tags.outputs.docker-tags }}

      - name: ğŸ‹ Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.nginx
          push: ${{ steps.release.outputs.release_created == 'true' || github.event_name == 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max